// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2zYrzHOxTRQxFkdZGmQ5Uog2sCQfxOOw',
    appId: '1:333507641175:web:060e7a543768bed38b4812',
    messagingSenderId: '333507641175',
    projectId: 'church-for-us',
    authDomain: 'church-for-us.firebaseapp.com',
    storageBucket: 'church-for-us.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfOeXpRQbTAbUPIVpiCgNXYMmupRs0Ot0',
    appId: '1:333507641175:android:c11cc1cdfe9bece48b4812',
    messagingSenderId: '333507641175',
    projectId: 'church-for-us',
    storageBucket: 'church-for-us.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDYOkQVSv_Lgt-k1WxNdh5N0EAEsYDIrA',
    appId: '1:333507641175:ios:fc76e06650c0c4498b4812',
    messagingSenderId: '333507641175',
    projectId: 'church-for-us',
    storageBucket: 'church-for-us.appspot.com',
    iosBundleId: 'com.example.churchStream',
  );
}
